[2024-02-07T21:50:29.432+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lighthouse_challenge.extracts.teste manual__2024-02-07T21:50:28.124090+00:00 [queued]>
[2024-02-07T21:50:29.435+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lighthouse_challenge.extracts.teste manual__2024-02-07T21:50:28.124090+00:00 [queued]>
[2024-02-07T21:50:29.435+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-07T21:50:29.443+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extracts.teste> on 2024-02-07 21:50:28.124090+00:00
[2024-02-07T21:50:29.452+0000] {standard_task_runner.py:60} INFO - Started process 702 to run task
[2024-02-07T21:50:29.456+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lighthouse_challenge', 'extracts.teste', 'manual__2024-02-07T21:50:28.124090+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0ve69bkk']
[2024-02-07T21:50:29.458+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask extracts.teste
[2024-02-07T21:50:29.483+0000] {task_command.py:423} INFO - Running <TaskInstance: lighthouse_challenge.extracts.teste manual__2024-02-07T21:50:28.124090+00:00 [running]> on host 98e8e7f947a8
[2024-02-07T21:50:29.513+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lighthouse_challenge' AIRFLOW_CTX_TASK_ID='extracts.teste' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T21:50:28.124090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T21:50:28.124090+00:00'
[2024-02-07T21:50:29.514+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-07T21:50:29.515+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'meltano run extract-csv']
[2024-02-07T21:50:29.520+0000] {subprocess.py:86} INFO - Output:
[2024-02-07T21:50:29.531+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: meltano: command not found
[2024-02-07T21:50:29.531+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-02-07T21:50:29.536+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-07T21:50:29.537+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=lighthouse_challenge, task_id=extracts.teste, execution_date=20240207T215028, start_date=20240207T215029, end_date=20240207T215029
[2024-02-07T21:50:29.544+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task extracts.teste (Bash command failed. The command returned a non-zero exit code 127.; 702)
[2024-02-07T21:50:29.555+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-07T21:50:29.569+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
